name: Generate Snooker Graphs

on:
  schedule:
    # Run once an hour
    - cron: '0 * * * *'
  # Allow manual trigger via GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker build -t snooker-project .

      - name: Run script and generate graphs
        env:
          GDRIVE_API_KEY: ${{ secrets.GDRIVE_API_KEY }}
        run: |
          docker run --rm -v $(pwd):/app snooker-project

      - name: Commit and push new images
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add game_wins.png
          git commit -m "Automated graph update" || echo "No changes to commit"
          git push
